name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'
      - run: yarnpkg --pure-lockfile
      - run: yarnpkg build
      - run: yarnpkg lint
      - run: yarnpkg test --coverage

  build-binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64]
        include:
        - goos: darwin
          goarch: arm64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.25.0'
      - run: yarnpkg --pure-lockfile
      - run: yarnpkg build
      - run: go build ./cmd/dsadmin
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}

